---

- name: Zip all the certificate files for {{ acme_domain }}
  become: true
  community.general.archive:
    path: "{{ acme_files_dir }}"
    dest: "{{ acme_files_dir }}/wildcard.{{ base_domain }}.zip"
    owner: "{{ ansible_user }}"
    mode: "644"
  delegate_to: localhost
  run_once: true

- name: Send certificates via SMTP for {{ acme_domain }}
  become: true
  community.general.mail:
    host: "{{ acme_collect_mail.smtp_server }}"
    port: "{{ acme_collect_mail.smtp_port }}"
    # username: your_email@example.com
    # password: your_password
    from: "{{ acme_collect_mail.sender }}"
    to: "{{ acme_collect_mail.recipient }}"
    subject: "Let's Encrypt Certificate Files of {{ acme_domain }}"
    body: "DNS-01 ACME challenge using FortiADC is successful. Check all the certificate files in the attachment."
    attach:
      - "{{ acme_files_dir }}/wildcard.{{ base_domain }}.zip"
  delegate_to: localhost
  run_once: true
