---

- name: Make sure the needed directory exists.
  ansible.builtin.file:
    path: "{{ acme_files_dir }}"
    state: directory
  delegate_to: localhost
  run_once: true

- name: Generate an OpenSSL RSA 4096 private key for account for {{ item.base_domain }}.
  community.crypto.openssl_privatekey:
    path: "{{ acme_private_account_key_dir }}"
    size: 4096
    type: RSA
  delegate_to: localhost
  run_once: true

- name: Generate an OpenSSL RSA 4096 private key for CSR for {{ item.base_domain }}.
  community.crypto.openssl_privatekey:
    path: "{{ acme_private_cert_key_dir }}"
    size: 4096
    type: RSA
  delegate_to: localhost
  run_once: true

- name: Generate an OpenSSL Certificate Signing Request for {{ item.base_domain }}.
  community.crypto.openssl_csr:
    path: "{{ acme_csr_dir }}"
    privatekey_path: "{{ acme_private_cert_key_dir }}"
    country_name: "{{ cert_country_id }}"
    common_name: "{{ item.base_domain }}"
    organization_name: "{{ cert_org_name }}"
    email_address: "{{ acme_account_email }}"
    subject_alt_name: "{{ cert_san | map('regex_replace', '^', 'DNS:') | list }}"
  delegate_to: localhost
  run_once: true