---

- name: Generate an OpenSSL RSA 4096 private key for account.
  community.crypto.openssl_privatekey:
    path: "{{ acme_private_account_key_dir }}"
    size: 4096
    type: RSA

- name: Generate an OpenSSL RSA 4096 private key for CSR.
  community.crypto.openssl_privatekey:
    path: "{{ acme_private_cert_key_dir }}"
    size: 4096
    type: RSA

- name: Generate an OpenSSL Certificate Signing Request.
  community.crypto.openssl_csr:
    path: "{{ acme_csr_dir }}"
    privatekey_path: "{{ acme_private_cert_key_dir }}"
    country_name: "{{ cert_country_id }}"
    common_name: "{{ base_domain }}"
    organization_name: "{{ cert_org_name }}"
    email_address: "{{ acme_account_email }}"
    subject_alt_name: "{{ cert_san | map('regex_replace', '^', 'DNS:') | list }}"