---
# ./tasks/main.yaml

- name: Include pre-task tasks.
  include_tasks: pre_task.yaml
  when: "'certificate-server' in group_names"

- name: Include tasks to generate private key and CSR.
  include_tasks: generate_private_key_and_csr.yaml
  when: "'certificate-server' in group_names"

- name: Include tasks to do DNS-01 ACME challenge using FortiADC.
  include_tasks: fad_acme_dns_challenge.yaml
