---

- name: Make sure OpenSSL and python-pip is installed.
  ansible.builtin.package:
    name: "{{ acme_server_packages }}"
    state: present
    update_cache: true
  run_once: true

- name: Make sure the needed pip module is installed.
  ansible.builtin.pip:
    name: "{{ acme_pip_packages }}"
    state: present
  run_once: true
