---
name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
      - name: Lint all the yaml.
        uses: ibiqlik/action-yamlint@v3
